### PR TITLE
Psr2 and fixes

### PR DESCRIPTION
**Pull request by joecohens**
This PR makes the library follow the http://www.php-fig.org/psr/psr-2/ and fixed the tests that were failing. Also can we enable TravisCI on this package?

I think it would be cool to start working on a version 2.0 and start working with namespaces.

/cc @MauricioMurga @leofischer

### CODE REVIEW

**Comment by MauricioMurga** [comment]
@joecohens, it is kind of hard for me to check the changes in this PR since spacing is mixed with code fixes. Could you separate the code fixes from spacing changes?

Thanks

**Comment by joecohens** [comment]
@MauricioMurga here you go only the third commit has the tests fixes the other two have cs fixes https://github.com/joecohens/conekta-php/commit/f8841f3297a1cca5acd6acec7ca616c77f517192

**Comment by MauricioMurga** [comment]
Thanks @joecohens for the PR. We will probably use https://codeship.com. Does that work for you?

**Comment by joecohens** [comment]
:beers: Yeah Codeship it's good, also you should take a look to CircleCI. We use TravisCI for the open source projects, but tbh any one of them it's perfect.

**Pull request merged**
