### PR TITLE
bugfix/disabled-php_uname

### PR DESCRIPTION
**Pull request by 0zuna**
bugfix/disabled-php_uname

### CODE REVIEW

**Comment by fcarrero** [comment]
please change the main branch to master

**Comment by 0zuna** [comment]
is done!

**Comment by fcarrero** [comment]
close in favor of 
https://github.com/conekta/conekta-php/pull/241/files

**Comment by 0zuna** [comment]
@fcarrero You stole my code contribution, leaving me out of the list of contributors

**Comment by fcarrero** [comment]
new php-sdk is based on openapi generator
https://github.com/conekta/openapi/pull/53

then, many files are generated based on this repository, we don't modify directly those files

**Pull request closed without merging**
