### PR TITLE
Update CHANGELOG and README

### PR DESCRIPTION
**Pull request by ErickZH**
Update CHANGELOG and README

* Added links for releases
* Added link for changelog

### CODE REVIEW

**Comment by leofischer** [comment]
This makes sense, thanks @ErickZH!

**Comment by ErickZH** [comment]
@leofischer I would like to contribute to the API documentation 😅

**Comment by leofischer** [comment]
Hi @ErickZH,

Sorry for the delay, I was hoping to push a bunch of improvements to our docs before replying (the changes are now live, including improved array syntax for PHP).  We would be delighted to have you contribute, what type of changes would you like to make?  Right now our documentation repo is private, so I will need to check with the team first grant you access.

**Comment by ErickZH** [comment]
Hi @leofischer 

I would like to contribute to the documentation of the tutorials, webhooks, API, etc.

**Pull request merged**
